name: setup-nillion-action-test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-action:
    name: setup-nillion actions test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test nillion setup action
        id: test-action
        uses: ./
        with:
          version: latest

      - run: echo "${{ steps.test-action.outputs.nada-version }}"
      - run: echo "${{ steps.test-action.outputs.nillion-devent-version }}"
      - run: echo "${{ steps.test-action.outputs.nillion-version }}"
      - run: echo "${{ steps.test-action.outputs.nilup-version }}"
      - run: echo "${{ steps.test-action.outputs.pynadac-version }}"
